### ISSUE TITLE
Click on curtainLinks has a delay

### ISSUE THREAD

**Issue by hahnmg** [Victa/curtain.js#25]
I tested this in all major browsers and it's always the same. Nearly 2 seconds until the slides change. 
Tried to clear the animation queue (line 469) with http://api.jquery.com/clearQueue/ but this destroys the script. 

Any suggestions?

**Comment by Victa** [comment]
I tryed your code. It doesn't work fine because you use the plugin called "localscroll".
I think it's no compliant with Curtain, because Curtain uses a very specific code to scroll inside the page (margin-top) and localscroll can't recognize this.
Last thing, I don't understand why you add the plugin scrollTo? 
And one suggestion : update to v2 here https://github.com/Victa/curtain.js/tree/development/v2.0

**Comment by hahnmg** [comment]
I am so sorry I wasted your time.  
Those two plugins were still there from an earlier version…  

Thank you so much.  

## 

Alexander Hahn

Am Mittwoch, 19. September 2012 um 16:20 schrieb Victor Coulon:
